esphome:
  name: air-quality-monitor
  platform: ESP32
  board: esp32dev
  includes:
    - zh03b.h
  libraries:
    # Tidak perlu library tambahan

wifi:
  ssid: "YourWiFiSSID"
  password: "YourWiFiPassword"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# UART configuration untuk ZH03B
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# Custom sensor component
external_components:
  - source:
      type: local
      path: my_components

sensor:
  # Mode Passive (default) - sensor mengirim data otomatis
  - platform: zh03b
    uart_id: uart_0
    mode: PASSIVE  # atau QA untuk mode Question & Answer
    update_interval: 30s
    pm_1_0:
      name: "PM1.0"
      id: pm1
    pm_2_5:
      name: "PM2.5"
      id: pm25
    pm_10_0:
      name: "PM10.0"
      id: pm10

  # Contoh dengan mode Q&A - lebih hemat power
  # - platform: zh03b
  #   uart_id: uart_0
  #   mode: QA
  #   update_interval: 60s  # Interval request data
  #   pm_1_0:
  #     name: "PM1.0 QA"
  #   pm_2_5:
  #     name: "PM2.5 QA"
  #   pm_10_0:
  #     name: "PM10.0 QA"