esphome:
  name: air-quality-monitor
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "YourWiFiSSID"
  password: "YourWiFiPassword"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# UART configuration untuk ZH03B
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# Custom sensor component - Pilih salah satu method di bawah

# Method 1: External Components (GitHub - untuk repo public)
external_components:
  - source: github://Bjk8kds/esphome-zh03b-sensor
    components: [ zh03b ]

# Method 2: Local Components (untuk development)
# external_components:
#   - source:
#       type: local
#       path: components
#     components: [ zh03b ]

sensor:
  # Mode Passive (default) - sensor mengirim data otomatis
  - platform: zh03b
    uart_id: uart_bus
    mode: PASSIVE  # atau QA untuk mode Question & Answer
    pm_1_0:
      name: "PM1.0"
      id: pm1
    pm_2_5:
      name: "PM2.5"
      id: pm25
    pm_10_0:
      name: "PM10.0"
      id: pm10

  # Contoh dengan mode Q&A - lebih hemat power
  # - platform: zh03b
  #   uart_id: uart_bus
  #   mode: QA
  #   pm_1_0:
  #     name: "PM1.0 QA"
  #   pm_2_5:
  #     name: "PM2.5 QA"
  #   pm_10_0:
  #     name: "PM10.0 QA"

# Optional: Advanced configuration
# logger:
#   level: DEBUG
#   logs:
#     zh03b: DEBUG  # Enable debug untuk troubleshooting

# Optional: Status sensors
# binary_sensor:
#   - platform: status
#     name: "ZH03B Status"

# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: "IP Address"
